name = "sparforte"
description = "An open source scripting language for high integrity tasks"
version = "3.0.1"
tags = ["scripting", "language"]

authors = ["Ken Burtch <ken@pegasoft.ca>"]
maintainers = ["Pascal Pignard <blady.net@orange.fr>"]
maintainers-logins = ["Blady-Com"]
website = "http://sparforte.com"

licenses = "GPL-2.0-only"

executables = ["spar"]

[environment]
TERM.set = "xterm-256color"

[[actions]]
type = "post-fetch"
command = ["sh", "configure", "--without-bdb", "--without-mysql", "--without-opengl",
                              "--without-postgres", "--without-readline", "--without-sound",
                              "--without-pcre", "--without-sdl", "--arch=native"]

[origin]
commit = "0b48f708c638996e8d4ff3a83c527219055ac08c"
url = "git+https://github.com/Blady-Com/SparForte.git"

